apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gcip
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gcip
    app.kubernetes.io/part-of: byoc-app-tytq
  name: gcip
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: gcip
status:
  loadBalancer: {}
